apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-orders
  labels:
    app: store-orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-orders
  template:
    metadata:
      labels:
        app: store-orders
    spec:
      containers:
        - name: store-orders
          image: kalatunga/store-orders
          resources:
            requests:
              memory: "250Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb
                  key: database-name
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-password
---
apiVersion: v1
kind: Service
metadata:
  name: store-orders
  labels:
    app: store-orders
spec:
  ports:
    - port: 8001
      protocol: TCP
      nodePort: 31001
  selector:
    app: store-orders
  type: NodePort

# NEVER FORGET
# $ minikube addons enable ingress

