apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: store-orders
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: store-orders
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
