apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: store-products
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: store-products
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
